name: 'article-markdown-auto-translate'
description: "Automatically translate markdown files with google translater."
author: 'budblack'
inputs:
  newsLink:
    description: 'A string in a specific format that contains a link to a article.'
    required: true
  ignoreSelector:
    description: 'CSS selector of elements which should be ignored'
  markDownFilePath:
    description: 'Path of the generated MarkDown file and relative path relative to the root folder.'
    required: true
    default: './'
  githubToken:
    description: ' GitHub  write and read token,auto create,no need to set'
    default: ''

runs:
  using: 'node20'
  main: 'bin/index.js'